const archiveData = [
  {
    name: "Anime & Manga",
    short: "a",
    link: "https://desuarchive.org/a/",
    boardtype: "blue",
  },
  {
    name: "Adult Cartoons",
    short: "aco",
    link: "https://desuarchive.org/aco/",
    boardtype: "red",
  },
  {
    name: "Animals & Nature",
    short: "an",
    link: "https://desuarchive.org/an/",
    boardtype: "blue",
  },
  {
    name: "Random",
    short: "b",
    link: "https://boards.4channel.org/b",
    boardtype: "red",
  },
  {
    name: "Anime/Cute",
    short: "c",
    link: "https://desuarchive.org/c/",
    boardtype: "blue",
  },
  {
    name: "Cosplay & EGL",
    short: "cgl",
    link: "https://desuarchive.org/cgl/",
    boardtype: "blue",
  },
  {
    name: "Comics & Cartoons",
    short: "co",
    link: "https://desuarchive.org/co/",
    boardtype: "blue",
  },
  {
    name: "Alternative",
    short: "d",
    link: "https://desuarchive.org/d/",
    boardtype: "red",
  },
  {
    name: "Fitness",
    short: "fit",
    link: "https://desuarchive.org/fit/",
    boardtype: "blue",
  },
  {
    name: "Technology",
    short: "g",
    link: "https://desuarchive.org/g/",
    boardtype: "blue",
  },
  {
    name: "History & Humanities",
    short: "his",
    link: "https://desuarchive.org/his/",
    boardtype: "blue",
  },
  {
    name: "International",
    short: "int",
    link: "https://desuarchive.org/int/",
    boardtype: "blue",
  },
  {
    name: "Weapons",
    short: "k",
    link: "https://desuarchive.org/k/",
    boardtype: "blue",
  },
  {
    name: "Mecha",
    short: "m",
    link: "https://desuarchive.org/m/",
    boardtype: "blue",
  },
  {
    name: "Pony",
    short: "mlp",
    link: "https://desuarchive.org/mlp/",
    boardtype: "blue",
  },
  {
    name: "Music",
    short: "mu",
    link: "https://desuarchive.org/mu/",
    boardtype: "blue",
  },
  {
    name: "4chan Feedback",
    short: "q",
    link: "https://desuarchive.org/q/",
    boardtype: "blue",
  },
  {
    name: "Question & Answer",
    short: "qa",
    link: "https://desuarchive.org/qa/",
    boardtype: "blue",
  },
  {
    name: "ROBOT9001",
    short: "r9k",
    link: "https://desuarchive.org/r9k/",
    boardtype: "blue",
  },
  {
    name: "Traditional Games",
    short: "tg",
    link: "https://desuarchive.org/tg/",
    boardtype: "blue",
  },
  {
    name: "Off-Topic",
    short: "trash",
    link: "https://desuarchive.org/trash/",
    boardtype: "red",
  },
  {
    name: "Retro Games",
    short: "vr",
    link: "https://desuarchive.org/vr/",
    boardtype: "blue",
  },
  {
    name: "Worksafe GIF",
    short: "wsg",
    link: "https://desuarchive.org/wsg/",
    boardtype: "blue",
  },
];

export default archiveData;
